// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1032:Implémenter des constructeurs d'exception standard", Justification = "<En attente>", Scope = "type", Target = "~T:SimpleInjector.Internals.CyclicDependencyException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Spécifier StringComparison", Justification = "<En attente>", Scope = "member", Target = "~M:SimpleInjector.Types.ToFriendlyName(System.Type,System.Boolean,System.Func{System.Type[],System.String})~System.String")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1001:Les types qui ont des champs supprimables doivent être supprimables", Justification = "<En attente>", Scope = "type", Target = "~T:SimpleInjector.ContainerScope")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Spécifier StringComparison", Justification = "<En attente>", Scope = "member", Target = "~M:SimpleInjector.Internals.ParameterDictionary`1.ParameterInfoComparer.GetHashCode(System.Reflection.ParameterInfo)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Spécifier StringComparison", Justification = "<En attente>", Scope = "member", Target = "~M:SimpleInjector.Internals.ParameterDictionary`1.ParameterInfoComparer.GetHashCode(System.Reflection.MemberInfo)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1033:Les méthodes d'interface doivent pouvoir être appelées par les types enfants", Justification = "<En attente>", Scope = "member", Target = "~M:SimpleInjector.Scope.System#IServiceProvider#GetService(System.Type)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1040:Éviter les interfaces vides", Justification = "<En attente>", Scope = "type", Target = "~T:System.IEvent")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Ne pas intercepter les types d'exception générale", Justification = "<En attente>", Scope = "member", Target = "~M:System.Design.DependencyInjection.ServiceProviderHelpers.GetServiceOrCreateInstance(System.IServiceProvider,System.Type)~System.Optional{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Ne pas intercepter les types d'exception générale", Justification = "<En attente>", Scope = "member", Target = "~M:System.Design.DependencyInjection.ServiceProviderHelpers.CreateInstance(System.IServiceProvider,System.Type,System.Object[])~System.Optional{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Ne pas intercepter les types d'exception générale", Justification = "<En attente>", Scope = "member", Target = "~M:System.Design.DependencyInjection.ServiceProviderHelpers.GetInstance(System.IServiceProvider,Microsoft.Extensions.DependencyInjection.ServiceDescriptor)~System.Optional{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Ne pas intercepter les types d'exception générale", Justification = "<En attente>", Scope = "member", Target = "~M:System.Design.DependencyInjection.ServiceProviderHelpers.WithFactory(Microsoft.Extensions.DependencyInjection.ServiceDescriptor,System.Func{System.IServiceProvider,System.Object})~System.Optional{Microsoft.Extensions.DependencyInjection.ServiceDescriptor}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Ne pas intercepter les types d'exception générale", Justification = "<En attente>", Scope = "member", Target = "~M:System.Design.DependencyInjection.ServiceProviderExtensions.WithFactory(Microsoft.Extensions.DependencyInjection.ServiceDescriptor,System.Func{System.IServiceProvider,System.Object})~System.Optional{Microsoft.Extensions.DependencyInjection.ServiceDescriptor}")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<En attente>", Scope = "member", Target = "~M:System.Design.DependencyInjection.ServiceProviderExtensions.CreateInstance(System.IServiceProvider,System.Type,System.Object[])~System.Optional{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<En attente>", Scope = "member", Target = "~M:System.Design.DependencyInjection.ServiceProviderExtensions.GetInstance(System.IServiceProvider,Microsoft.Extensions.DependencyInjection.ServiceDescriptor)~System.Optional{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<En attente>", Scope = "member", Target = "~M:System.Design.DependencyInjection.ServiceProviderExtensions.GetServiceOrCreateInstance(System.IServiceProvider,System.Type)~System.Optional{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Ne pas intercepter les types d'exception générale", Justification = "<En attente>", Scope = "member", Target = "~M:System.StringGenerator.Generate(System.Int32,System.String)~System.Optional{System.String}")]
