// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Les identificateurs doivent avoir un suffixe correct", Justification = "<En attente>", Scope = "type", Target = "~T:System.Optional`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Les identificateurs ne doivent pas correspondre à des mots clés", Justification = "<En attente>", Scope = "type", Target = "~T:System.Optional`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2225:Les surcharges d'opérateur offrent d'autres méthodes nommées", Justification = "<En attente>", Scope = "member", Target = "~M:System.Optional`1.op_Implicit(System.Optional{`0})~`0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2225:Les surcharges d'opérateur offrent d'autres méthodes nommées", Justification = "<En attente>", Scope = "member", Target = "~M:System.Optional`1.op_Implicit(System.Optional{`0})~System.Threading.Tasks.Task{System.Optional{`0}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2225:Les surcharges d'opérateur offrent d'autres méthodes nommées", Justification = "<En attente>", Scope = "member", Target = "~M:System.Optional`1.op_Implicit(System.Optional{`0})~System.Threading.Tasks.ValueTask{System.Optional{`0}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1030:Utiliser des événements quand cela est approprié", Justification = "<En attente>", Scope = "member", Target = "~M:System.Design.IEventDispatcher.RaiseEventAsync(System.Design.IEvent,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1030:Utiliser des événements quand cela est approprié", Justification = "<En attente>", Scope = "member", Target = "~M:System.Design.IEventDispatcher.RaiseEventAsync``1(``0,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1030:Utiliser des événements quand cela est approprié", Justification = "<En attente>", Scope = "member", Target = "~M:System.Design.EventDispatcher.RaiseEventAsync``1(``0,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1030:Utiliser des événements quand cela est approprié", Justification = "<En attente>", Scope = "member", Target = "~M:System.Design.EventDispatcher.RaiseEventAsync(System.Design.IEvent,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1030:Utiliser des événements quand cela est approprié", Justification = "<En attente>", Scope = "member", Target = "~M:System.Design.IEventDispatcher.RaiseEventAsync(System.Design.IEvent)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1030:Utiliser des événements quand cela est approprié", Justification = "<En attente>", Scope = "member", Target = "~M:System.Design.IEventDispatcher.RaiseEventAsync``1(``0)~System.Threading.Tasks.Task")]